//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSC_Ticket_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket
    {
        public int Ticket_ID { get; set; }
        [Required(ErrorMessage = "*Required")]
        public string Ticket_Title { get; set; }
        [Required(ErrorMessage = "*Required")]
        [DataType(DataType.MultilineText)]
        public string Ticket_Description { get; set; }
        public string Ticket_Status { get; set; }
        public string CREATED_BY { get; set; }
        public int Ticket_Admin { get; set; }
    
        public virtual User User { get; set; }
    }
}
